---
title: "Assignment 6"
author: "BIOL1007A"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
 
## Data wrangling and plotting

1. Using the built-in `starwars` data set in the `dplyr` package, create a new tibble with the following modifications: 

+ It only includes the species that have more than 1 individual represented in the data set. 
(hint: first use `dplyr` to summarize the number of individuals per species in the data frame; then create a vector/tibble of those names; subset the species that are included in that vector)  

+ It only includes the columns that are not of type list (hint: use glimpse to check)

2. Clean your data set: only include observations/rows that do not have an `NA` in the height column. Then, use `dplyr` to print a summary table showing the mean, median, and standard deviation of height for **each species.** 

3. Create a box plot figure that shows the variation in heights among Star Wars species. Do the values in your summary table line up with the plot? Code so that each box plot (Species) is be filled with a different color. Change your axes labels so that species is capitalized and height is capitalized and shows units (cm). Use the theme_minimal option. Then look into the `annotate` or `geom_text` functions and add the text "p=1.2E-0.5" to the top right corner. 

*For an extra (optional) challenge:* overlay the data points onto the box plots (hint: look into `geom_jitter` or `geom_point`). See if you can change the color of the points, depending on the gender or sex variables.  

4. Using the same or a different built-in data set, create at least one additional (and different kind of) plot. Experiment with different arguments, features, and colors.

5. Finally, create a multi-panel figure with the graphs you created.
